package com.vue.model;

public class Vue {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vue.id
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vue.username
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vue.email
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vue.sex
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vue.province
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vue.hobby
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    private String hobby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vue.id
     *
     * @return the value of vue.id
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */

    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vue.id
     *
     * @param id the value for vue.id
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vue.username
     *
     * @return the value of vue.username
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vue.username
     *
     * @param username the value for vue.username
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vue.email
     *
     * @return the value of vue.email
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vue.email
     *
     * @param email the value for vue.email
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vue.sex
     *
     * @return the value of vue.sex
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vue.sex
     *
     * @param sex the value for vue.sex
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vue.province
     *
     * @return the value of vue.province
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vue.province
     *
     * @param province the value for vue.province
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vue.hobby
     *
     * @return the value of vue.hobby
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vue.hobby
     *
     * @param hobby the value for vue.hobby
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }
}