package com.lx.vuecrud.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.id
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.username
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.email
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.sex
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.province
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.hobby
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.id
     *
     * @return the value of v_user.id
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public User withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.id
     *
     * @param id the value for v_user.id
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.username
     *
     * @return the value of v_user.username
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public User withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.username
     *
     * @param username the value for v_user.username
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.email
     *
     * @return the value of v_user.email
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public User withEmail(String email) {
        this.setEmail(email);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.email
     *
     * @param email the value for v_user.email
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.sex
     *
     * @return the value of v_user.sex
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public User withSex(String sex) {
        this.setSex(sex);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.sex
     *
     * @param sex the value for v_user.sex
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.province
     *
     * @return the value of v_user.province
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public User withProvince(String province) {
        this.setProvince(province);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.province
     *
     * @param province the value for v_user.province
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.hobby
     *
     * @return the value of v_user.hobby
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public User withHobby(String hobby) {
        this.setHobby(hobby);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.hobby
     *
     * @param hobby the value for v_user.hobby
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated Tue Dec 24 23:16:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", email=").append(email);
        sb.append(", sex=").append(sex);
        sb.append(", province=").append(province);
        sb.append(", hobby=").append(hobby);
        sb.append("]");
        return sb.toString();
    }
}