package com.vue.mapper;

import com.vue.model.Vue;
import com.vue.model.VueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    long countByExample(VueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int deleteByExample(VueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int insert(Vue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int insertSelective(Vue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    List<Vue> selectByExampleWithRowbounds(VueExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    List<Vue> selectByExample(VueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    Vue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") Vue record, @Param("example") VueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int updateByExample(@Param("record") Vue record, @Param("example") VueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int updateByPrimaryKeySelective(Vue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vue
     *
     * @mbg.generated Fri Dec 27 12:36:26 CST 2019
     */
    int updateByPrimaryKey(Vue record);
}